#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

ROOT=$DIR/../
SRC=$ROOT/src/

#
# Build directory structure and clone submodules.
# These may be included as proper git submodules later on.
#

# build
git clone --depth 10 https://chromium.googlesource.com/chromium/src/build $SRC/build

# blink
mkdir -p $SRC/third_party
git clone --depth 10 https://chromium.googlesource.com/chromium/blink $SRC/third_party/WebKit

# third_party other than blink
git clone --depth 10 https://chromium.googlesource.com/chromium/deps/icu52 $SRC/third_party/icu

# tools (some are included with src repo, others come from separate repos)
mkdir -p $SRC/tools
git clone --depth 10 https://chromium.googlesource.com/external/grit-i18n.git    $SRC/tools/grit
git clone --depth 10 https://chromium.googlesource.com/external/gyp.git          $SRC/tools/gyp
git clone --depth 10 https://chromium.googlesource.com/chromium/src/tools/clang  $SRC/tools/clang

# install ./src/third_party/llvm-build
./src/tools/clang/scripts/update.sh

## PATCHES
### WebKit
(cd $SRC/third_party/WebKit/                                                                 \
  && git apply $ROOT/patches/0001-removing-unit_test-build-from-WebKit-config-targets.patch  \
  && git apply $ROOT/patches/0002-disabling-all-targets-but-inspector_protocol_resourc.patch \
)
